apiVersion: 1

datasources:
  - name: tempo
    type: tempo
    url: http://tempo:3200
    editable: true

  - name: jaeger
    type: jaeger
    url: http://jaeger:16686
    editable: true
  
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
      - name: trace_id
        datasourceUid: jaeger