apiVersion: v1
kind: Pod
metadata:
  labels:
    component: prometheus
  name: prometheus
spec:
  containers:
  - args:
    - --web.console.templates=/etc/prometheus/consoles
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --storage.tsdb.retention.time=20m
    - --config.file=/etc/prometheus-config.yaml
    - --storage.tsdb.path=/prometheus
    - --web.enable-lifecycle
    - --web.route-prefix=/
    - --enable-feature=exemplar-storage
    image: quay.io/prometheus/prometheus:v2.43.0
    imagePullPolicy: IfNotPresent
    name: prometheus
    volumeMounts:
    - mountPath: /etc/prometheus-config.yaml
      name: config
      readOnly: true
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  volumes:
  - hostPath:
      path: /etc/prometheus-config.yaml
      type: File
    name: config