apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otel-collector
  namespace: default
spec:
  serviceName: otel-collector
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetry-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: opentelemetry-collector
          args:
            - --config=/conf/relay.yaml
          image: otel/opentelemetry-collector-contrib:0.90.1
          imagePullPolicy: Never
          ports:
            - name: otlp
              containerPort: 4317
              protocol: TCP
          volumeMounts:
            - mountPath: /conf
              name: opentelemetry-collector-configmap
      hostNetwork: true
      volumes:
        - name: opentelemetry-collector-configmap
          configMap:
            name: otel-config
            items:
              - key: relay
                path: relay.yaml
